### ISSUE TITLE
wrong message during bracket testing

### ISSUE THREAD

**Issue by saberpowers** [elishayer/mRchmadness#14]
After the bracket has been found, when it is being tested, as illustrated below, the dialogue box says, "Finding you bracket". It should read "Testing your bracket".

![image](https://user-images.githubusercontent.com/20248701/37075738-7135c804-2190-11e8-8138-203468f8a2f3.png)

**Comment by elishayer** [comment]
I do not see this in my local version. The gif below shows this working as expected.

![mar-09-2018 02-15-24](https://user-images.githubusercontent.com/9312768/37202621-e23f96d2-233f-11e8-828c-715d18641b3d.gif)

I do, however, get the error below when clicking "Find Best Bracket." Do you not get this?

```
Warning: Error in strsplit: non-character argument
Stack trace (innermost first):
    108: strsplit
    107: function_list[[i]]
    106: freduce
    105: _fseq
    104: eval
    103: eval
    102: withVisible
    101: %>%
    100: mRchmadness::draw.bracket
     99: shiny::renderPlot [/Users/elishayer/GitHub/mRchmadness/inst/shinyApp/server.R#22]
     89: <reactive:plotObj>
     78: plotObj
     77: origRenderFunc
     76: output$bracket.empty.plot
      1: shiny::runApp
```

**Comment by saberpowers** [comment]
Locally I'm getting the same behavior as you. What I posted above is from the shinyapps.io-hosted app. I'll try re-deploying the app online after I fix the bug that's causing the "non-character argument" error.

**Comment by saberpowers** [comment]
Now the app hosted on shinyapps.io exhibits the desired behavior, and the "non-character argument" bug was fixed by https://github.com/elishayer/mRchmadness/commit/d4b5f05f1dbd84993bd552ebf589fb86985c69ed.
