### ISSUE TITLE
If a team_id isn't in the list of teams test.bracket returns NA

### ISSUE THREAD

**Issue by mattmills49** [elishayer/mRchmadness#24]
I was using `test.bracket` on a custom bracket where I had Syracuse winning a first round matchup and had them as `"183"` in the custom bracket without realizing I needed to list both teams (`"9/183"`) in my custom bracket. The issue is that the `seed[bracket.picks]` call (in the `score.bracket` function here: https://github.com/elishayer/mRchmadness/blob/master/R/score.bracket.R#L42) returns an `NA` value. So if the team_id is wrong then that `NA` value gets rolled up and their score is `NA` for each simulation. I'm not saying I'm doing it "right" haha but I think an error should be thrown alerting the user that one of their team_ids is wrong, by typo or a misunderstanding.

**Comment by elishayer** [comment]
I agree we should handle this better. We'll throw an error.
