### ISSUE TITLE
Using 538 model

### ISSUE THREAD

**Issue by rmassemich** [elishayer/mRchmadness#33]
Is there a way to use the 538 model in predicting the bracket as opposed to the Bradley-Terry model with the package?

**Comment by elishayer** [comment]
The effort is a little higher than I'll be able to put towards it this year. I would welcome a PR. The steps would be:
1. download the data from https://projects.fivethirtyeight.com/2022-march-madness-predictions/
2. shape them into the R structure we've used in the past for 538
3. Call `save(...)` to create the RData file with the appropriate name and variable name
4. Map the teams by team name in the 538 column of the team map variable, and again call `save(...)` on the teams to update that RData file

**Comment by cbranch117** [comment]
@rmassemich @elishayer 
So I forked and cloned the repository; I've got the three pred.___.men.2022 files, but I'm running into some issues when trying to run it on my machine, most likely with your #4. I'll keep playing around with it.
"Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed"

**Comment by saberpowers** [comment]
This is closed by #38! 538 predictions are now available in 2023 for both men's and women's tournaments! And hopefully this will be easier to accomplish more quickly in future years.
