### ISSUE TITLE
add 2018 brackets to package

### ISSUE THREAD

**Issue by saberpowers** [elishayer/mRchmadness#6]
The men's bracket is to be announced on March 11. The women's bracket is to be announced on March 12. This issue is to add these brackets to `data/bracket.men.2018.RData` and `data/bracket.women.2018.RData` once they are announced. Also add documentation to `R/bracket.men.2018.R` and `R/bracket.women.2018.R`.

**Comment by saberpowers** [comment]
I've added a stand-in for the 2018 men's bracket using [Joe Lunardi's Bracketology](http://www.espn.com/mens-college-basketball/bracketology). I'll soon do the same for the 2018 women's bracket using [Charlie Creme's Bracketology](http://www.espn.com/womens-college-basketball/bracketology).

**Comment by saberpowers** [comment]
Stand-in for 2018 women's bracket added.

**Comment by elishayer** [comment]
Men's 2018 bracket was added in https://github.com/elishayer/mRchmadness/commit/968197665b4672638482d3d2455136f942ece567.
