### ISSUE TITLE
scrape population picks for 2018

### ISSUE THREAD

**Issue by saberpowers** [elishayer/mRchmadness#8]
Use the `scrape.population.distribution()` function to get ESPN population picks. We'll want to re-do this scraping each day from the announcement of the brackets to the beginning of the tournament, re-building the package with patch increments to the semantic versioning each time. The population picks should be saved as `data/pred.pop.men.2018.RData` and `data/pred.pop.women.2018.RData`. Also add documentation to `R/pred.pop.men.2018.R` and `R/pred.pop.women.2018.R`.

**Comment by elishayer** [comment]
Closing as complete from the two commits above. Had been holding it open for 3 years waiting on ESPN to provide the women's bracket population picks, but unfortunately we're still waiting.

![image](https://user-images.githubusercontent.com/9312768/110243242-26681080-7f1f-11eb-9070-345e60fc4dd0.png)
